# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_PreprocessorDlg.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_PreprocessorDlg(object):
    def setupUi(self, PreprocessorDlg):
        PreprocessorDlg.setObjectName("PreprocessorDlg")
        PreprocessorDlg.resize(781, 441)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PreprocessorDlg.sizePolicy().hasHeightForWidth())
        PreprocessorDlg.setSizePolicy(sizePolicy)
        PreprocessorDlg.setMinimumSize(QtCore.QSize(781, 400))
        PreprocessorDlg.setMaximumSize(QtCore.QSize(781, 471))
        self.horizontalLayoutWidget = QtWidgets.QWidget(PreprocessorDlg)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(450, 400, 320, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnLoad = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnLoad.setObjectName("btnLoad")
        self.horizontalLayout_4.addWidget(self.btnLoad)
        self.btnSave = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnSave.setObjectName("btnSave")
        self.horizontalLayout_4.addWidget(self.btnSave)
        self.btnRun = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnRun.setObjectName("btnRun")
        self.horizontalLayout_4.addWidget(self.btnRun)
        self.btnExit = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.btnExit.setObjectName("btnExit")
        self.horizontalLayout_4.addWidget(self.btnExit)
        self.label_3 = QtWidgets.QLabel(PreprocessorDlg)
        self.label_3.setGeometry(QtCore.QRect(10, 10, 761, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setWordWrap(True)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(PreprocessorDlg)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setWordWrap(True)
        self.label_4.setObjectName("label_4")
        self.gridLayoutWidget = QtWidgets.QWidget(PreprocessorDlg)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 360, 241, 71))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtEasting = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtEasting.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtEasting.setObjectName("txtEasting")
        self.gridLayout.addWidget(self.txtEasting, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 1)
        self.txtNorthing = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.txtNorthing.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtNorthing.setObjectName("txtNorthing")
        self.gridLayout.addWidget(self.txtNorthing, 1, 1, 1, 1)
        self.label = QtWidgets.QLabel(PreprocessorDlg)
        self.label.setGeometry(QtCore.QRect(10, 320, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.txtNumCol = QtWidgets.QLineEdit(PreprocessorDlg)
        self.txtNumCol.setGeometry(QtCore.QRect(270, 50, 81, 20))
        self.txtNumCol.setText("")
        self.txtNumCol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.txtNumCol.setObjectName("txtNumCol")
        self.tblInstructions = QtWidgets.QTableWidget(PreprocessorDlg)
        self.tblInstructions.setGeometry(QtCore.QRect(10, 80, 763, 231))
        self.tblInstructions.setAlternatingRowColors(True)
        self.tblInstructions.setRowCount(50)
        self.tblInstructions.setColumnCount(9)
        self.tblInstructions.setObjectName("tblInstructions")
        item = QtWidgets.QTableWidgetItem()
        self.tblInstructions.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInstructions.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInstructions.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInstructions.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInstructions.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInstructions.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInstructions.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInstructions.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblInstructions.setHorizontalHeaderItem(8, item)
        self.tblInstructions.horizontalHeader().setDefaultSectionSize(80)
        self.tblInstructions.verticalHeader().setVisible(True)
        self.tblInstructions.verticalHeader().setDefaultSectionSize(20)
        self.tblInstructions.verticalHeader().setMinimumSectionSize(20)
        self.progressBar = QtWidgets.QProgressBar(PreprocessorDlg)
        self.progressBar.setGeometry(QtCore.QRect(450, 360, 321, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")

        self.retranslateUi(PreprocessorDlg)
        QtCore.QMetaObject.connectSlotsByName(PreprocessorDlg)

    def retranslateUi(self, PreprocessorDlg):
        _translate = QtCore.QCoreApplication.translate
        PreprocessorDlg.setWindowTitle(_translate("PreprocessorDlg", "Sensor Data File Instructions"))
        self.btnLoad.setText(_translate("PreprocessorDlg", "Load File"))
        self.btnSave.setText(_translate("PreprocessorDlg", "Save File"))
        self.btnRun.setText(_translate("PreprocessorDlg", "Run"))
        self.btnExit.setText(_translate("PreprocessorDlg", "Exit"))
        self.label_3.setText(_translate("PreprocessorDlg", "Enter the instructions for reading a comma delimited sensor data file.  Enter the sensor offsets from the GPS receiver in meters.  Assume the vehicle faces due north when entering offsets."))
        self.label_4.setText(_translate("PreprocessorDlg", "Enter the total number of columns in the file:"))
        self.label_2.setText(_translate("PreprocessorDlg", "Easting:"))
        self.txtEasting.setText(_translate("PreprocessorDlg", "0.0"))
        self.label_5.setText(_translate("PreprocessorDlg", "Northing:"))
        self.txtNorthing.setText(_translate("PreprocessorDlg", "0.0"))
        self.label.setText(_translate("PreprocessorDlg", "Enter coordinate offset from the vehicle GPS system to the field map, if any:"))
        item = self.tblInstructions.horizontalHeaderItem(0)
        item.setText(_translate("PreprocessorDlg", "Sensor\n"
"Name"))
        item = self.tblInstructions.horizontalHeaderItem(1)
        item.setText(_translate("PreprocessorDlg", "Latitude\n"
"Column #"))
        item = self.tblInstructions.horizontalHeaderItem(2)
        item.setText(_translate("PreprocessorDlg", "Longitude\n"
"Column #"))
        item = self.tblInstructions.horizontalHeaderItem(3)
        item.setText(_translate("PreprocessorDlg", "Heading\n"
"Column #"))
        item = self.tblInstructions.horizontalHeaderItem(4)
        item.setText(_translate("PreprocessorDlg", "Sensor ID\n"
"Column #"))
        item = self.tblInstructions.horizontalHeaderItem(5)
        item.setText(_translate("PreprocessorDlg", "Sensor ID\n"
"Text"))
        item = self.tblInstructions.horizontalHeaderItem(6)
        item.setText(_translate("PreprocessorDlg", "Data\n"
"Column #(s)"))
        item = self.tblInstructions.horizontalHeaderItem(7)
        item.setText(_translate("PreprocessorDlg", "Easting\n"
"Offset (m)"))
        item = self.tblInstructions.horizontalHeaderItem(8)
        item.setText(_translate("PreprocessorDlg", "Northing\n"
"Offset (m)"))

